-- Phase 2 post-UAT correction: distinguish content-thin failures from
-- transient LLM-call failures so the renderer can route them to the
-- footer aside vs an in-place "summary couldn't be generated this week"
-- card per the PROJECT.md LOCKED directive.
--
-- summary_status values:
--   ok                 — tldr present
--   thin               — content too thin (pre-check or model returned empty)
--   quota_exhausted    — 429 / RESOURCE_EXHAUSTED from the LLM provider
--   api_error          — non-quota API failure (timeout, 5xx, network)
--   parse_error        — LLM returned content that didn't parse as JSON
--   client_init_error  — LLM client setup failed (rare)
--
-- Old rows have NULL summary_status; the renderer treats NULL as
-- equivalent to inferring from tldr/summary_confidence so historical
-- weeks still render without backfill.
ALTER TABLE item_summaries ADD COLUMN summary_status TEXT;
